POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ardi_c_cc@hotmail.com",
    "password": "12345678"
}

###

GET http://localhost:5000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJkaWFucyIsImVtYWlsIjoiYXJkaV9jX2NjQGhvdG1haWwuY29tIiwiaWQiOiI1ZTQyZDkzMjFmNjUzMDIzZDQyNGZiMTUiLCJpYXQiOjE1ODI0NzIzMDgsImV4cCI6MTU4MjQ3MjMzOH0.eBiWxuxPCuVshLeX941n-2apEGo8RzreVLHavF218So

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "ardian2",
    "email": "ardiansallauka2@hotmail.com",
    "password": "12345678",
    "password2": "12345678"
}

###

DELETE http://localhost:5000/articles/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJkaWFucyIsImVtYWlsIjoiYXJkaV9jX2NjQGhvdG1haWwuY29tIiwiaWQiOiI1ZTQyZDkzMjFmNjUzMDIzZDQyNGZiMTUiLCJpYXQiOjE1ODI0NzIyMjcsImV4cCI6MTU4MjQ3MjI1N30.aRqoIxmqrKjpvMk0p0EBUqLiw99Zk4yqiYJGflSl8-k

{
    "id": "5e52948a49c1b40017c89a0e"
}
###

POST http://localhost:5000/articles/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJkaWFucyIsImVtYWlsIjoiYXJkaV9jX2NjQGhvdG1haWwuY29tIiwiaWQiOiI1ZTQyZDkzMjFmNjUzMDIzZDQyNGZiMTUiLCJpYXQiOjE1ODI0NzIyODgsImV4cCI6MTU4MjQ3MjMxOH0.bRBZdCNRrKtnSX61GfiWQmrydA4dZ-LLyiJxEZsngfg

{
    "id": "5e42db89a27bf01cd42bb3df",
    "title": "Robots related article --- (Changed)",
    "body": "Some quote from robot (Changed)."
}